#!/bin/bash
# default mode is worker

MODE="worker"
HOST_IP=""

if [ $1 == "master" ]; then
    MODE=$1
    if [ -z $2 ]; then
        echo "If this is a master node, please specify the host ip (this machine) as third parameters"
        echo "Example: 
            ./setup master <YOUR_HOST_IP>"
        exit 1
    fi
    HOST_IP=$2
fi

echo "Step - 1: Installing docker..."

apt-get remove docker docker-engine docker.io containerd runc
apt-get update
apt-get install -y \
   apt-transport-https \
   ca-certificates \
   curl \
   gnupg \
   lsb-release

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
 "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
 $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install -y docker-ce=5:20.10.8~3-0~ubuntu-hirsute docker-ce-cli=5:20.10.8~3-0~ubuntu-hirsute containerd.io

# add this config if using private docker registry
# "insecure-registries": ["192.168.10.62:6004"],
cat > /etc/docker/daemon.json <<EOF
{
    "exec-opts": ["native.cgroupdriver=systemd"],
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "100m"
    },
    "storage-driver": "overlay2"
}
EOF
systemctl daemon-reload
systemctl restart docker
echo "Step - 1: Docker installation & configuration done!"

echo "Step - 2: Installing Kubernetes components..."
apt-get update
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update
swapoff -a

apt-get install -qy kubelet=1.22.3-00 kubeadm=1.22.3-00 kubectl=1.22.3-00
echo "Step - 3: Starting Kubernetes Cluster..."

if [ $MODE = "master" ]; then
    echo "Starting master node..."
    kubeadm init --apiserver-advertise-address=${HOST_IP} --pod-network-cidr=192.168.0.0/16
    echo "Snooze for a while until kubectl config is ready..."
    sleep 10

    rm -rf ~/.kube
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
    echo "copy done!"

    echo "Installing Calico CNI..."
    kubectl apply -f ./calico/1_tigera-operator.yaml
    # Let's slow down a bit until tigera operator is ready
    sleep 20
    kubectl apply -f ./calico/2_custom-resources.yaml

    echo "Installing MetalLB..."
    kubectl apply -f ./metallb/1_namespace.yaml
    kubectl apply -f ./metallb/2_metallb.yaml
    kubectl apply -f ./metallb/3_cluster.yaml

    echo "Installing ingress-nginx..."
    kubectl apply -f ./ingress-nginx/ingress-nginx-controller.yaml

    echo "Step - 3: Congratulations, Your Kubernetes cluster is up!"
fi
