apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-nfs-pvc1
spec:
  # storageClassName: manual
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
